services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      QUARKUS_LOG_HANDLER_GELF_ENABLED: true
      QUARKUS_LOG_HANDLER_GELF_HOST: graylog
      QUARKUS_LOG_HANDLER_GELF_PORT: 12201

  elasticsearch:
    image: docker.io/elastic/elasticsearch:7.17.16
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      http.host: "0.0.0.0"
      discovery.type: "single-node"
      xpack.security.enabled: false
      cluster.routing.allocation.disk.threshold_enabled: false

  mongo:
    image: mongo:7.0.5

  graylog:
    image: graylog/graylog:5.2.3
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "1514:1514"
    environment:
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_PASSWORD_SECRET: "forpasswordencryption"
      # admin
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
      GRAYLOG_MONGODB_URI: mongodb://mongo:27017/graylog
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - mongo
